// Copyright (c) Breachline UE. All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "Engine/DataTable.h"
#include "BreachlineSettings.generated.h"

class UNiagaraSystem;
class UStaticMesh;
class UInputMappingContext;
class USoundClass;

UENUM(BlueprintType)
enum class EBreachlineQuality : uint8
{
	Low		UMETA(DisplayName = "Low (handheld / integrated)"),
	Medium	UMETA(DisplayName = "Medium (console / Lumen Lite)"),
	High	UMETA(DisplayName = "High (Lumen + MegaLights + VSM)")
};

/**
 * Project Settings > Game > Breachline.
 *
 * Every asset reference is SOFT and optional: the game boots and plays with an
 * empty Content folder because each subsystem falls back to its procedural
 * implementation (blockout geometry, Niagara-less tracers, C++ synth audio, a
 * code-drawn HUD). Drop real assets in, point the settings here, and the same
 * code paths light them up — no logic changes.
 */
UCLASS(config = Game, defaultconfig, meta = (DisplayName = "Breachline"))
class BREACHLINEUE_API UBreachlineSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	UBreachlineSettings();

	virtual FName GetCategoryName() const override { return TEXT("Game"); }

	// --- Data ---------------------------------------------------------------
	/** Rows of FBreachlineWeaponDef. Empty -> Breachline::DefaultWeapons(). */
	UPROPERTY(config, EditAnywhere, Category = "Data", meta = (DisplayName = "Weapon Table"))
	TSoftObjectPtr<UDataTable> WeaponTable;

	/** Rows of FEnemyArchetypeDef. Empty -> Breachline::DefaultEnemyArchetypes(). */
	UPROPERTY(config, EditAnywhere, Category = "Data", meta = (DisplayName = "Enemy Archetype Table"))
	TSoftObjectPtr<UDataTable> EnemyTable;

	/** Rows of FRoundDef. Empty -> Breachline::DefaultRounds(). */
	UPROPERTY(config, EditAnywhere, Category = "Data", meta = (DisplayName = "Round Table"))
	TSoftObjectPtr<UDataTable> RoundTable;

	UPROPERTY(config, EditAnywhere, Category = "Data")
	FString WeaponTablePath = TEXT("/Game/Breachline/Data/DT_Weapons.DT_Weapons");

	UPROPERTY(config, EditAnywhere, Category = "Data")
	FString EnemyTablePath = TEXT("/Game/Breachline/Data/DT_Enemies.DT_Enemies");

	UPROPERTY(config, EditAnywhere, Category = "Data")
	FString RoundTablePath = TEXT("/Game/Breachline/Data/DT_Rounds.DT_Rounds");

	// --- Input --------------------------------------------------------------
	/** Generated by Content/Python/breachline_assets.py. */
	UPROPERTY(config, EditAnywhere, Category = "Input")
	TSoftObjectPtr<UInputMappingContext> DefaultMappingContext;

	UPROPERTY(config, EditAnywhere, Category = "Input")
	FString MappingContextPath = TEXT("/Game/Breachline/Input/IMC_Breachline.IMC_Breachline");

	// --- Presentation -------------------------------------------------------
	/** Environment kit: blockout meshes swapped for production art. */
	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UStaticMesh> WallMesh;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UStaticMesh> BuildingMesh;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UStaticMesh> CrateMesh;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UStaticMesh> SandbagMesh;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UStaticMesh> BarrelMesh;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UStaticMesh> HealthKitMesh;

	/** Niagara systems; when unset the FX subsystem draws ribbons/decals instead. */
	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UNiagaraSystem> MuzzleFlashFX;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UNiagaraSystem> ImpactFX;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UNiagaraSystem> TracerFX;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UNiagaraSystem> ExplosionFX;

	UPROPERTY(config, EditAnywhere, Category = "Presentation")
	TSoftObjectPtr<UNiagaraSystem> AmbientDustFX;

	// --- Tuning -------------------------------------------------------------
	UPROPERTY(config, EditAnywhere, Category = "Tuning", meta = (ClampMin = "0.5", ClampMax = "2.0"))
	float PlayerDamageTakenMult = 1.f;

	UPROPERTY(config, EditAnywhere, Category = "Tuning", meta = (ClampMin = "0.5", ClampMax = "2.0"))
	float EnemyDamageTakenMult = 1.f;

	UPROPERTY(config, EditAnywhere, Category = "Tuning", meta = (ClampMin = "1", ClampMax = "12"))
	int32 MaxCorpses = 10;

	UPROPERTY(config, EditAnywhere, Category = "Tuning", meta = (ClampMin = "1.0", ClampMax = "20.0"))
	float CorpseLifetimeSeconds = 6.f;

	UPROPERTY(config, EditAnywhere, Category = "Tuning", meta = (ClampMin = "0", ClampMax = "12"))
	int32 EnemiesPerSpawnWave = 1;

	/** Simulated between rounds when the player is behind cover. */
	UPROPERTY(config, EditAnywhere, Category = "Tuning")
	bool bShowRadarAlways = false;

	/** Helpers: resolve a table by its configured path, or nullptr. */
	UDataTable* ResolveWeaponTable() const;
	UDataTable* ResolveEnemyTable() const;
	UDataTable* ResolveRoundTable() const;

	static const UBreachlineSettings* Get();
};
